/**
 * Фікстура для dev-галереї: усі 79 облич каталогу з маркерами й здібностями.
 *
 * Не імпортуємо `src/back/data/cards.json` — він поза пакетом фронта, `tsconfig`
 * туди не дотягнеться. І не перезаписуємо `src/front/data/cards.json` справжнім
 * каталогом: `lib/cards.ts` будує `heroesById` за полем `h.id`, якого в справжньому
 * файлі немає — усі 72 герої схлопнулись би в один запис із ключем `undefined`.
 *
 * Згенеровано з src/back/data/cards.json тим самим правилом, що й `setup.py`:
 * герої отримують id за позицією в масиві, поле `fraction` перейменовується на `faction`.
 */

import type { CardCatalogEntry } from "../../types";

export type GalleryCard = {
  cardId: string;
  name: string;
  faction: string;
  fraction_1?: string;
  fraction_2?: string;
};

export const GALLERY_HEROES: readonly GalleryCard[] = [
  { cardId: "hero_0", name: "Shaky Sharpshooter", faction: "Highlanders" },
  { cardId: "hero_1", name: "Depressed Druid", faction: "Highlanders" },
  { cardId: "hero_2", name: "Cave Keeper", faction: "Highlanders" },
  { cardId: "hero_3", name: "Dreamy Hermit", faction: "Highlanders" },
  { cardId: "hero_4", name: "Long-eared Loner", faction: "Highlanders" },
  { cardId: "hero_5", name: "Saber Tooth Troll", faction: "Highlanders" },
  { cardId: "hero_6", name: "Intimidating Tribesman", faction: "Highlanders" },
  { cardId: "hero_7", name: "Spirited Shaman", faction: "Highlanders" },
  { cardId: "hero_8", name: "Grumpy Guard", faction: "Highlanders" },
  { cardId: "hero_9", name: "Righteous Battle Maid", faction: "Highlanders" },
  { cardId: "hero_10", name: "Hangry Barbarian", faction: "Highlanders" },
  { cardId: "hero_11", name: "Joyless Chief", faction: "Highlanders" },
  { cardId: "hero_12", name: "Familiar Handler", faction: "Highlanders" },
  { cardId: "hero_13", name: "Curious Troll", faction: "Highlanders" },
  { cardId: "hero_14", name: "Furious Pigman", faction: "Highlanders" },
  { cardId: "hero_15", name: "Bored Goblin", faction: "Highlanders" },
  { cardId: "hero_16", name: "Curious Cat Lover", faction: "Highlanders" },
  { cardId: "hero_17", name: "Warty Witch", faction: "Highlanders" },
  { cardId: "hero_18", name: "Short-sighted Soldier", faction: "Imperials" },
  { cardId: "hero_19", name: "Doubtful Priest", faction: "Imperials" },
  { cardId: "hero_20", name: "Underestimated Squire", faction: "Imperials" },
  { cardId: "hero_21", name: "Flailing Knight", faction: "Imperials" },
  { cardId: "hero_22", name: "Underpaid Mercenary", faction: "Imperials" },
  { cardId: "hero_23", name: "Heart Bending Bard", faction: "Imperials" },
  { cardId: "hero_24", name: "Modest Monsterslayer", faction: "Imperials" },
  { cardId: "hero_25", name: "Ace Fighter", faction: "Imperials" },
  { cardId: "hero_26", name: "Battle Connoisseur", faction: "Imperials" },
  { cardId: "hero_27", name: "Canned Cavalier", faction: "Imperials" },
  { cardId: "hero_28", name: "Whiskered Viking", faction: "Imperials" },
  { cardId: "hero_29", name: "Almost-evil Scholar", faction: "Imperials" },
  { cardId: "hero_30", name: "Well-aged Warrior", faction: "Imperials" },
  { cardId: "hero_31", name: "Androgynous Assassin", faction: "Imperials" },
  { cardId: "hero_32", name: "Groggy Preacher", faction: "Imperials" },
  { cardId: "hero_33", name: "Queer Quartermaster", faction: "Imperials" },
  { cardId: "hero_34", name: "Angry Priestess", faction: "Imperials" },
  { cardId: "hero_35", name: "Resilient Rearguard", faction: "Imperials" },
  { cardId: "hero_36", name: "Bony Target Practice", faction: "Undead" },
  { cardId: "hero_37", name: "Unconfident Executioner", faction: "Undead" },
  { cardId: "hero_38", name: "Ghastly Granny", faction: "Undead" },
  { cardId: "hero_39", name: "Apish Honorguard", faction: "Undead" },
  { cardId: "hero_40", name: "Half-headed Wizard", faction: "Undead" },
  { cardId: "hero_41", name: "Nightmarish Northman", faction: "Undead" },
  { cardId: "hero_42", name: "Half-eaten Bull", faction: "Undead" },
  { cardId: "hero_43", name: "Gorgeous Gorgon", faction: "Undead" },
  { cardId: "hero_44", name: "Raven Whisperer", faction: "Undead" },
  { cardId: "hero_45", name: "Insidious Impaler", faction: "Undead" },
  { cardId: "hero_46", name: "Well Instructed Mummy", faction: "Undead" },
  { cardId: "hero_47", name: "Will-bending Witch", faction: "Undead" },
  { cardId: "hero_48", name: "Resurrected Ram", faction: "Undead" },
  { cardId: "hero_49", name: "Mummy Mystic", faction: "Undead" },
  { cardId: "hero_50", name: "Notorious Necromancer", faction: "Undead" },
  { cardId: "hero_51", name: "Sun-shy Skeleton", faction: "Undead" },
  { cardId: "hero_52", name: "Wrapped Warrior", faction: "Undead" },
  { cardId: "hero_53", name: "Sluggish Slimemonster", faction: "Undead" },
  { cardId: "hero_54", name: "Pessimistic Whaleman", faction: "Waterfolk" },
  { cardId: "hero_55", name: "Tentacled Oracle", faction: "Waterfolk" },
  { cardId: "hero_56", name: "Drowned Deserter", faction: "Waterfolk" },
  { cardId: "hero_57", name: "Deep Sea Squire", faction: "Waterfolk" },
  { cardId: "hero_58", name: "Vegetarian Sharkguard", faction: "Waterfolk" },
  { cardId: "hero_59", name: "Double Shielded Turtle", faction: "Waterfolk" },
  { cardId: "hero_60", name: "Leery Lizard", faction: "Waterfolk" },
  { cardId: "hero_61", name: "Furious Frog", faction: "Waterfolk" },
  { cardId: "hero_62", name: "Apathetic Waterpriest", faction: "Waterfolk" },
  { cardId: "hero_63", name: "Hopeful Salamander", faction: "Waterfolk" },
  { cardId: "hero_64", name: "Fearsome Fishman", faction: "Waterfolk" },
  { cardId: "hero_65", name: "Triple Sword Lizard", faction: "Waterfolk" },
  { cardId: "hero_66", name: "Saltwater Sage", faction: "Waterfolk" },
  { cardId: "hero_67", name: "Minor Fishguard", faction: "Waterfolk" },
  { cardId: "hero_68", name: "Clamped Krill Guard", faction: "Waterfolk" },
  { cardId: "hero_69", name: "Aimless Eel", faction: "Waterfolk" },
  { cardId: "hero_70", name: "Bludgeoning Blowfish", faction: "Waterfolk" },
  { cardId: "hero_71", name: "Voodoo Witch", faction: "Waterfolk" },
];

export const GALLERY_LEADERS: readonly GalleryCard[] = [
  { cardId: "leader_pavyr", name: "Pavyr", faction: "Leader", fraction_1: "Highlanders", fraction_2: "Imperials" },
  { cardId: "leader_myrad", name: "Myrad", faction: "Leader", fraction_1: "Undead", fraction_2: "Highlanders" },
  { cardId: "leader_lemron", name: "Lemron", faction: "Leader", fraction_1: "Waterfolk", fraction_2: "Highlanders" },
  { cardId: "leader_cyra", name: "Cyra", faction: "Leader", fraction_1: "Waterfolk", fraction_2: "Imperials" },
  { cardId: "leader_xiadul", name: "Xiadul", faction: "Leader", fraction_1: "Imperials", fraction_2: "Undead" },
  { cardId: "leader_enned", name: "Enned", faction: "Leader", fraction_1: "Waterfolk", fraction_2: "Undead" },
];

export const GALLERY_JOKER: GalleryCard = { cardId: "deceased_emperor", name: "Deceased Emperor", faction: "Joker" };

export const GALLERY_FACTIONS = ["Highlanders", "Imperials", "Undead", "Waterfolk"] as const;

/** Той самий вигляд, у якому каталог приходить із проєкції бекенда. */
export const GALLERY_CATALOG: Record<string, CardCatalogEntry> = {
  "hero_0": {"name": "Shaky Sharpshooter", "faction": "Highlanders", "markers": {"red": 1, "green": 0, "logic": "AND"}, "ability": {"action": "Kill", "target_player": "other", "target_zone": "Party", "visibility": "face_down", "filters": {"fraction": "Undead"}}},
  "hero_1": {"name": "Depressed Druid", "faction": "Highlanders", "markers": {"red": -2, "green": -1, "logic": "AND"}},
  "hero_2": {"name": "Cave Keeper", "faction": "Highlanders", "markers": {"red": 0, "green": 2, "logic": "AND"}, "ability": {"action": "Condition", "condition": "no_red_in_tavern"}},
  "hero_3": {"name": "Dreamy Hermit", "faction": "Highlanders", "markers": {"red": 0, "green": 1, "logic": "OR", "green_alt": 2}, "ability": {"action": "Condition", "condition": "green_behind_red"}},
  "hero_4": {"name": "Long-eared Loner", "faction": "Highlanders", "markers": {"red": 0, "green": 1, "logic": "AND"}, "ability": {"action": "Flip", "target_player": "other", "target_zone": "Party"}},
  "hero_5": {"name": "Saber Tooth Troll", "faction": "Highlanders", "markers": {"red": 0, "green": 2, "logic": "OR_NEG"}, "ability": {"action": "Swap", "source": "other_party", "target": "self_hand", "visibility": "face_up"}},
  "hero_6": {"name": "Intimidating Tribesman", "faction": "Highlanders", "markers": {"red": "X", "green": 0, "logic": "AND"}, "ability": {"action": "Calculation", "x_source": "target_party_markers"}},
  "hero_7": {"name": "Spirited Shaman", "faction": "Highlanders", "markers": {"red": 0, "green": 2, "logic": "AND"}, "ability": {"action": "Condition", "condition": "has_blue_black_party"}},
  "hero_8": {"name": "Grumpy Guard", "faction": "Highlanders", "markers": {"red": 0, "green": 1, "logic": "AND"}, "ability": {"action": "Draw", "source": ["Harbor", "Tavern"], "count": 3}},
  "hero_9": {"name": "Righteous Battle Maid", "faction": "Highlanders", "markers": {"red": 1, "green": -1, "logic": "OR"}, "ability": {"action": "Bury", "target_player": "other", "target_zone": "Party", "visibility": "any"}},
  "hero_10": {"name": "Hangry Barbarian", "faction": "Highlanders", "markers": {"red": 0, "green": "X", "logic": "AND"}, "ability": {"action": "Calculation", "x_source": "tavern_not_red"}},
  "hero_11": {"name": "Joyless Chief", "faction": "Highlanders", "markers": {"red": 0, "green": -1, "logic": "AND"}, "ability": {"action": "Draw", "source": "Tavern", "count": 2, "distribution": {"Party": 1, "Wilderness": 1}}},
  "hero_12": {"name": "Familiar Handler", "faction": "Highlanders", "markers": {"red": 1, "green": 1, "logic": "AND"}, "ability": {"action": "Place", "source": "hand", "target": "Party", "visibility": "face_down"}},
  "hero_13": {"name": "Curious Troll", "faction": "Highlanders", "markers": {"red": -1, "green": 1, "logic": "OR"}, "ability": {"action": "Look", "target_player": "other", "target_zone": "Party", "count": 2, "visibility": "face_down"}},
  "hero_14": {"name": "Furious Pigman", "faction": "Highlanders", "markers": {"red": -1, "green": 1, "logic": "AND"}},
  "hero_15": {"name": "Bored Goblin", "faction": "Highlanders", "markers": {"red": -2, "green": 0, "logic": "AND"}, "ability": {"action": "Condition", "condition": "has_red_party"}},
  "hero_16": {"name": "Curious Cat Lover", "faction": "Highlanders", "markers": {"red": 1, "green": 0, "logic": "AND"}, "ability": {"action": "Draw", "source": "other_hand", "target": "Party", "visibility": "face_down"}},
  "hero_17": {"name": "Warty Witch", "faction": "Highlanders", "markers": {"red": -1, "green": -1, "logic": "AND"}, "ability": {"action": "Swap", "source": "hand", "target": "Party_face_down"}},
  "hero_18": {"name": "Short-sighted Soldier", "faction": "Imperials", "markers": {"red": 1, "green": -1, "logic": "AND"}},
  "hero_19": {"name": "Doubtful Priest", "faction": "Imperials", "markers": {"red": 2, "green": 0, "logic": "OR_NEG_DECIDE_LEFT"}, "ability": {"action": "PlayExtra", "filters": {"not_fraction": "Imperials"}}},
  "hero_20": {"name": "Underestimated Squire", "faction": "Imperials", "markers": {"red": 1, "green": 0, "logic": "AND"}, "ability": {"action": "Flip", "target_player": "other", "target_zone": "Party"}},
  "hero_21": {"name": "Flailing Knight", "faction": "Imperials", "markers": {"red": -1, "green": -2, "logic": "AND"}},
  "hero_22": {"name": "Underpaid Mercenary", "faction": "Imperials", "markers": {"red": 2, "green": 0, "logic": "AND"}, "ability": {"action": "Condition", "condition": "no_red_in_tavern"}},
  "hero_23": {"name": "Heart Bending Bard", "faction": "Imperials", "markers": {"red": "X", "green": 0, "logic": "AND"}, "ability": {"action": "Calculation", "x_source": "tavern_not_green"}},
  "hero_24": {"name": "Modest Monsterslayer", "faction": "Imperials", "markers": {"red": 1, "green": 0, "logic": "AND"}, "ability": {"action": "Draw", "source": ["Harbor", "Tavern"], "count": 3}},
  "hero_25": {"name": "Ace Fighter", "faction": "Imperials", "markers": {"red": 1, "green": 0, "logic": "OR", "red_alt": 2}, "ability": {"action": "Condition", "condition": "red_behind_green"}},
  "hero_26": {"name": "Battle Connoisseur", "faction": "Imperials", "markers": {"red": -1, "green": 0, "logic": "AND"}, "ability": {"action": "Draw", "source": "Harbor", "count": 2, "distribution": {"Party_face_down": 1, "Wilderness": 1}}},
  "hero_27": {"name": "Canned Cavalier", "faction": "Imperials", "markers": {"red": 0, "green": 1, "logic": "AND"}, "ability": {"action": "Kill", "target_zone": "Party", "visibility": "face_up", "filters": {"fraction": "Highlanders"}}},
  "hero_28": {"name": "Whiskered Viking", "faction": "Imperials", "markers": {"red": 2, "green": 0, "logic": "AND"}, "ability": {"action": "Condition", "condition": "has_face_down_undead"}},
  "hero_29": {"name": "Almost-evil Scholar", "faction": "Imperials", "markers": {"red": "-X", "green": 0, "logic": "AND"}, "ability": {"action": "Calculation", "x_source": "target_face_up_green"}},
  "hero_30": {"name": "Well-aged Warrior", "faction": "Imperials", "markers": {"red": 1, "green": 1, "logic": "AND"}, "ability": {"action": "Place", "source": "hand", "target": "Party", "visibility": "face_down"}},
  "hero_31": {"name": "Androgynous Assassin", "faction": "Imperials", "markers": {"red": -1, "green": 1, "logic": "OR"}, "ability": {"action": "Guess_Kill", "target_player": "other", "target_zone": "Party", "visibility": "face_down"}},
  "hero_32": {"name": "Groggy Preacher", "faction": "Imperials", "markers": {"red": 1, "green": -1, "logic": "OR"}, "ability": {"action": "Look", "target_player": "other", "target_zone": "Party", "count": 2, "visibility": "face_down"}},
  "hero_33": {"name": "Queer Quartermaster", "faction": "Imperials", "markers": {"red": -1, "green": -1, "logic": "AND"}, "ability": {"action": "Swap", "source": "face_up_party", "target": "hand"}},
  "hero_34": {"name": "Angry Priestess", "faction": "Imperials", "markers": {"red": 0, "green": -2, "logic": "AND"}, "ability": {"action": "Condition", "condition": "has_face_down_green"}},
  "hero_35": {"name": "Resilient Rearguard", "faction": "Imperials", "markers": {"red": 0, "green": 1, "logic": "AND"}, "ability": {"action": "Draw", "source": "other_hand", "target": "Party", "visibility": "face_down"}},
  "hero_36": {"name": "Bony Target Practice", "faction": "Undead", "markers": {"red": 2, "green": 2, "logic": "AND_OR"}},
  "hero_37": {"name": "Unconfident Executioner", "faction": "Undead", "markers": {"red": -1, "green": -1, "logic": "AND"}, "ability": {"action": "Kill", "target_zone": "Party", "visibility": "face_down"}},
  "hero_38": {"name": "Ghastly Granny", "faction": "Undead", "markers": {"red": 0, "green": 0, "logic": "AND"}, "ability": {"action": "Perform", "target_zone": "self_party", "visibility": "face_down"}},
  "hero_39": {"name": "Apish Honorguard", "faction": "Undead", "markers": {"red": 2, "green": 2, "logic": "OR"}},
  "hero_40": {"name": "Half-headed Wizard", "faction": "Undead", "markers": {"red": 1, "green": 1, "logic": "AND"}, "ability": {"action": "Swap", "source": "Tavern", "target": "other_party_face_down"}},
  "hero_41": {"name": "Nightmarish Northman", "faction": "Undead", "markers": {"red": 2, "green": 2, "logic": "OR"}, "ability": {"action": "Kill_Dual", "targets": ["self_face_down", "other_face_down"]}},
  "hero_42": {"name": "Half-eaten Bull", "faction": "Undead", "markers": {"red": 2, "green": 1, "logic": "AND"}, "ability": {"action": "Kill", "target_zone": "Party", "visibility": "face_up"}},
  "hero_43": {"name": "Gorgeous Gorgon", "faction": "Undead", "markers": {"red": -1, "green": -1, "logic": "OR"}, "ability": {"action": "Kill_Random", "target_player": "other", "target_zone": "Party", "visibility": "face_down"}},
  "hero_44": {"name": "Raven Whisperer", "faction": "Undead", "markers": {"red": -1, "green": -1, "logic": "AND"}, "ability": {"action": "Draw", "source": "Tavern", "count": 2, "distribution": {"Party_face_down": 1, "Wilderness": 1}}},
  "hero_45": {"name": "Insidious Impaler", "faction": "Undead", "markers": {"red": 0, "green": 0, "logic": "AND"}, "ability": {"action": "Bury_Perform", "source": "Tavern"}},
  "hero_46": {"name": "Well Instructed Mummy", "faction": "Undead", "markers": {"red": -1, "green": -1, "logic": "OR"}, "ability": {"action": "Place", "source": "hand", "target": "Party", "visibility": "face_down"}},
  "hero_47": {"name": "Will-bending Witch", "faction": "Undead", "markers": {"red": 1, "green": 1, "logic": "OR"}, "ability": {"action": "Swap_Hand", "target_player": "other"}},
  "hero_48": {"name": "Resurrected Ram", "faction": "Undead", "markers": {"red": 1, "green": 1, "logic": "AND"}, "ability": {"action": "Swap", "source": "Tavern", "target": "self_party_face_down"}},
  "hero_49": {"name": "Mummy Mystic", "faction": "Undead", "markers": {"red": 1, "green": 2, "logic": "AND"}, "ability": {"action": "Swap", "source": "Graveyard_top", "target": "self_party_face_down"}},
  "hero_50": {"name": "Notorious Necromancer", "faction": "Undead", "markers": {"red": "X", "green": "X", "logic": "AND"}, "ability": {"action": "Calculation", "x_source": "graveyard_count"}},
  "hero_51": {"name": "Sun-shy Skeleton", "faction": "Undead", "markers": {"red": 0, "green": 0, "logic": "AND"}, "ability": {"action": "Perform_Top", "source": "Graveyard"}},
  "hero_52": {"name": "Wrapped Warrior", "faction": "Undead", "markers": {"red": 1, "green": 1, "logic": "OR"}, "ability": {"action": "Draw", "source": "Graveyard", "count": 3}},
  "hero_53": {"name": "Sluggish Slimemonster", "faction": "Undead", "markers": {"red": -1, "green": -1, "logic": "OR"}, "ability": {"action": "Kill", "target_zone": "Party", "visibility": "face_down"}},
  "hero_54": {"name": "Pessimistic Whaleman", "faction": "Waterfolk", "markers": {"red": 1, "green": 1, "logic": "OR"}, "ability": {"action": "Draw", "source": "Tavern", "count": 2, "distribution": {"Party_face_down": 1, "Wilderness": 1}}},
  "hero_55": {"name": "Tentacled Oracle", "faction": "Waterfolk", "markers": {"red": -3, "green": -3, "logic": "AND"}, "ability": {"action": "Reveal_Harbor", "count": 4, "condition": "no_undead"}},
  "hero_56": {"name": "Drowned Deserter", "faction": "Waterfolk", "markers": {"red": 0, "green": 0, "logic": "LEADING_MARKER"}, "ability": {"action": "Move_Markers", "options": ["-1 leading", "+2 behind"]}},
  "hero_57": {"name": "Deep Sea Squire", "faction": "Waterfolk", "markers": {"red": 1, "green": 1, "logic": "OR"}, "ability": {"action": "Draw_All_Tavern", "distribution": {"Party_face_down": 1, "Wilderness": "rest"}}},
  "hero_58": {"name": "Vegetarian Sharkguard", "faction": "Waterfolk", "markers": {"red": 1, "green": 1, "logic": "AND"}, "ability": {"action": "Bury", "target_player": "other", "target_zone": "Party", "visibility": "any"}},
  "hero_59": {"name": "Double Shielded Turtle", "faction": "Waterfolk", "markers": {"red": "-X", "green": "-X", "logic": "OR"}, "ability": {"action": "Calculation", "x_source": "target_face_up_blue"}},
  "hero_60": {"name": "Leery Lizard", "faction": "Waterfolk", "markers": {"red": -1, "green": 0, "logic": "OR", "red_alt": -2}},
  "hero_61": {"name": "Furious Frog", "faction": "Waterfolk", "markers": {"red": -2, "green": -2, "logic": "AND_OR"}},
  "hero_62": {"name": "Apathetic Waterpriest", "faction": "Waterfolk", "markers": {"red": 0, "green": -1, "logic": "OR", "green_alt": -2}},
  "hero_63": {"name": "Hopeful Salamander", "faction": "Waterfolk", "markers": {"red": 1, "green": 1, "logic": "AND"}, "ability": {"action": "Draw", "source": "Tavern", "count": 1, "target": "Party", "visibility": "face_down"}},
  "hero_64": {"name": "Fearsome Fishman", "faction": "Waterfolk", "markers": {"red": 0, "green": 0, "logic": "LEADING_MARKER"}, "ability": {"action": "Move_Markers", "logic": "AND", "effects": ["-1 leading", "+1 behind"]}},
  "hero_65": {"name": "Triple Sword Lizard", "faction": "Waterfolk", "markers": {"red": 0, "green": 0, "logic": "LEADING_MARKER"}, "ability": {"action": "Move_Markers", "logic": "OR", "effects": ["-1 leading", "-3 leading"]}},
  "hero_66": {"name": "Saltwater Sage", "faction": "Waterfolk", "markers": {"red": 0, "green": 0, "logic": "AND"}, "ability": {"action": "Perform_Self", "target_zone": "Party", "visibility": "face_down"}},
  "hero_67": {"name": "Minor Fishguard", "faction": "Waterfolk", "markers": {"red": -1, "green": -1, "logic": "OR"}, "ability": {"action": "Look", "target_player": "other", "target_zone": "Party", "count": 2, "visibility": "face_down"}},
  "hero_68": {"name": "Clamped Krill Guard", "faction": "Waterfolk", "markers": {"red": "-X", "green": "-X", "logic": "AND"}, "ability": {"action": "Calculation", "x_source": "target_face_down_count"}},
  "hero_69": {"name": "Aimless Eel", "faction": "Waterfolk", "markers": {"red": 1, "green": 1, "logic": "OR"}, "ability": {"action": "Kill", "target_zone": "Party", "visibility": "face_up"}},
  "hero_70": {"name": "Bludgeoning Blowfish", "faction": "Waterfolk", "markers": {"red": 1, "green": 0, "logic": "OR", "red_alt": -1}, "ability": {"action": "Flip_Or_Look", "target_player": "other", "target_zone": "Party", "visibility": "face_down"}},
  "hero_71": {"name": "Voodoo Witch", "faction": "Waterfolk", "markers": {"red": -1, "green": 1, "logic": "OR"}, "ability": {"action": "Place", "source": "hand", "target": "Party", "visibility": "face_down"}},
  "leader_pavyr": {"name": "Pavyr", "faction": "Leader", "fraction_1": "Highlanders", "fraction_2": "Imperials", "leader_number": 5},
  "leader_myrad": {"name": "Myrad", "faction": "Leader", "fraction_1": "Undead", "fraction_2": "Highlanders", "leader_number": 3},
  "leader_lemron": {"name": "Lemron", "faction": "Leader", "fraction_1": "Waterfolk", "fraction_2": "Highlanders", "leader_number": 1},
  "leader_cyra": {"name": "Cyra", "faction": "Leader", "fraction_1": "Waterfolk", "fraction_2": "Imperials", "leader_number": 2},
  "leader_xiadul": {"name": "Xiadul", "faction": "Leader", "fraction_1": "Imperials", "fraction_2": "Undead", "leader_number": 4},
  "leader_enned": {"name": "Enned", "faction": "Leader", "fraction_1": "Waterfolk", "fraction_2": "Undead", "leader_number": 6},
  "deceased_emperor": { "name": "Deceased Emperor", "faction": "Joker" },
};
